import { create } from "zustand";

export const useLanguage = create((set) => ({
    lang: localStorage.getItem("lang") || "en",
    setLang: (lang) => {
        localStorage.setItem("lang", lang);
        set({ lang });
    },
}));

export const translations = {
    en: {
        dashboard: "Dashboard",
        subscription: "My Subscription",
        inventory: "Inventory",
        purchases: "Purchases",
        suppliers: "Suppliers",
        stock: "Stock",
        stock_logs: "Stock Logs",
        pos: "POS / Sales",
        branches: "My Branches",
        tables: "Tables & QR",
        products: "Products",
        categories: "Categories",
        order_history: "Order History",
        staff_roles: "Staff & Roles",
        users: "Users / Staff",
        roles: "Roles",
        permissions: "Role Permissions",
        plans: "Subscription Plans",
        reports: "Reports & Insights",
        sales_report: "Sales Report",
        expenses: "Expenses",
        best_sellers: "Best Sellers",
        settings: "Settings",
        business: "Business Ecosystem",
        logout: "Logout",
        profile: "My Profile",
        executive_dashboard: "Executive Insights Dashboard",
        real_time_metrics: "Real-time performance metrics for your coffee business network",
        apply_filters: "Apply Filters",
        search: "Search",
        recent_activity: "Recent Activity",
        view_all_orders: "View All Orders",
        no_data: "No data available",
        customer_overview: "Customer Overview",
        financial_summary: "Financial Summary",
        sales_performance: "Sales Performance",
        total: "Total",
        total_sales: "Total Sales",
        total_expenses: "Total Expenses",
        net_profit: "Net Profit",
        order_count: "Order Count",
        avg_transaction: "Avg Transaction",
        profit_margin: "Profit Margin",
        performance_trends: "Performance Trends",
        revenue: "Revenue",
        growth: "Growth",
        distribution: "Distribution",
        live: "Live",
        now: "just now",
        account_settings: "Account Settings",
        general_info: "General Information",
        full_name: "Full Name",
        email_address: "Email Address (Login ID)",
        security_settings: "Security Settings",
        new_password: "New Password",
        confirm_password: "Confirm Password",
        leave_blank: "Leave blank to keep current",
        save_changes: "Save Changes",
        active_account: "Active Account",
        branch: "Branch",
        business_label: "Business",
        order_no: "Order No",
        date: "Date",
        status: "Status",
        amount: "Amount",
        payment_method: "Payment",
        cashier: "Cashier",
        all: "All",
        pending: "Pending",
        paid: "Paid",
        cancelled: "Cancelled",
        view_details: "View Details",
        order_details: "Order Details",
        order_detail: "Order Detail",
        subtotal: "Subtotal",
        tax: "Tax",
        discount: "Discount",
        print: "Print",
        export: "Export",
        filter: "Filter",
        items: "items",
        no_orders: "No orders found",
        order_management: "Order Management",
        track_orders: "Track and manage your orders efficiently",
        avg_order_value: "Avg Order Value",
        this_month: "This Month",
        total_revenue: "Total Revenue",
        subscription_limits: "My Subscription & Limits",
        overview: "Overview",
        billing_history: "Billing History",
        current_trial: "Current Trial",
        current_package: "Current Package",
        package_30_day_trial: "30-DAY TRIAL",
        started: "Started",
        expires_on: "Expires On",
        no_expiry: "No Expiry",
        days_remaining: "days remaining",
        days_ago: "days ago",
        expired_label: "Expired",
        upgrade_plan: "Upgrade Plan",
        resource_utilization: "Resource Utilization",
        staff_seats: "Staff Seats",
        store_branches: "Store Branches",
        sku_capacity: "SKU Capacity (Products)",
        unlimited: "Unlimited",
        need_more_capacity: "Need more capacity? Upgrading takes less than 1 minute.",
        compare_plans: "Compare Plans",
        subscription_history: "Subscription History",
        history_desc: "All your past and current subscription periods.",
        refresh: "Refresh",
        price: "Price",
        duration: "Duration",
        not_available: "Not Available",
        current: "Current",
        maybe_later: "Maybe Later",
        next_confirm: "Next: Confirm Upgrade →",
        currently_active: "Currently Active",
        upgrade_picker_desc: "Select a plan that fits your growing business needs. Permissions and limits will be updated instantly.",
        upgrading_to: "Upgrading to",
        month: "month",
        relogin_required: "Re-login Required",
        relogin_desc: "Please logout and login again to activate your new permissions and features.",
        upgrade_success: "Upgrade Successful! 🎉",
        full_access_to: "You now have full access to",
        active_until: "Active Until",
        got_it: "Got it! 🚀",
        days: "days",
        one_time: "One-time",
        lifetime: "Lifetime",
        permanent_access: "Permanent Access",
        product_list: "Product List",
        add_new_product: "Add New Product",
        edit_product: "Edit Product",
        search_product: "Search product...",
        product_name: "Product Name",
        category_name: "Category Name",
        quantity: "Quantity",
        barcode: "Barcode",
        description: "Description",
        image: "Image",
        action: "Action",
        confirm_delete_product: "Are you sure you want to delete this product?",
        product_deleted: "Product deleted successfully",
        product_saved: "Product saved successfully",
        remove_data: "Remove data",
        confirm_remove_product: "Are you sure you want to remove this product?",
        total_products: "Total Products",
        menu_inventory: "Menu Inventory",
        add_new: "Add New",
        brand: "Brand",
        edit_product_title: "☕ Edit Product",
        new_menu_item: "☕ New Menu Item",
        sizes: "Sizes",
        add_size: "Add Size",
        addons: "Add-ons",
        add_addon: "Add Add-on",
        customize_coffee: "Customize Your Coffee / Options",
        mood: "Mood / Type",
        hot: "Hot",
        iced: "Iced",
        frappe: "Frappe",
        sizes_override_msg: "* If specific sizes are set below, they will override the Base Price in POS.",
        base_price_label: "Base Price",
        save_item: "Save Item",
        update_item: "Update Item",
        purchase: "Purchase",
        supplier: "Supplier",
        raw_material: "Raw Material",
        invoices: "Invoices",
        shop_managment: "Shop Management",
        table: "Table",
        product: "Product",
        category: "Category",
        sale: "Sale",
        order: "Order",
        user: "User",
        permission: "Permission",
        total_purchase: "Total Purchase",
        total_paid: "Total Paid",
        outstanding_balance: "Outstanding Balance",
        total_orders: "Total Orders",
        purchase_history: "Purchase History",
        new_purchase: "New Purchase",
        ref_no: "Ref #",
        paid_amount: "Paid Amount",
        balance: "Balance",
        save: "Save",
        cancel: "Cancel",
        receive_date: "Receive Date",
        note: "Note",
        total_amount: "Total Amount",
        receiving_now: "Receiving Now",
        supplier_list: "Supplier List",
        name: "Name",
        code: "Code",
        tel: "Tel",
        email: "Email",
        address: "Address",
        website: "Website",
        created_at: "Created At",
        edit: "Edit",
        delete: "Delete",
        add_new_supplier: "Add New Supplier",
        edit_supplier: "Edit Supplier",
        confirm_delete_supplier: "Are you sure you want to delete this supplier?",
        supplier_deleted: "Supplier deleted successfully!",
        raw_material_list: "Raw Material List",
        material_name: "Material Name",
        stock_status: "Stock Status",
        last_cost: "Last Cost",
        active: "Active",
        inactive: "Inactive",
        add_new_material: "Add New Material",
        edit_material: "Edit Material",
        initial_stock: "Initial Stock",
        min_stock_alert: "Min Stock Alert",
        in_stock: "IN STOCK",
        low_stock: "LOW STOCK",
        out_of_stock: "OUT OF STOCK",
        total_products_menu: "Total Products Menu",
        low_stock_products: "Low Stock Products",
        low_stock_materials: "Low Stock Materials",
        stock_logs_adjustments: "Stock Logs & Adjustments",
        manual_adjustment: "Manual Adjustment",
        filter_by_item_type: "Filter by Item Type",
        filter_by_type: "Filter by Type",
        date_time: "DateTime",
        category: "Category",
        transaction: "Transaction",
        change: "Change",
        staff: "Staff",
        reason: "Reason",
        stock_correction: "Stock Correction",
        inventory_item_type: "Inventory Item Type",
        select_item: "Select Item",
        action_type: "Action Type",
        qty_change: "Qty Change",
        remark_reason: "Remark / Reason",
        adjustment: "Adjustment",
        waste: "Waste",
        receive: "Receive",
        branch_management: "Branch Management",
        manage_locations: "Manage your business locations and headquarters",
        add_new_branch: "Add New Branch",
        branch_name: "Branch Name",
        location_address: "Location / Address",
        contact_phone: "Contact Phone",
        set_as_main_hq: "Set as Main HQ?",
        main_headquarter: "Main Headquarter",
        setup_new_branch: "Setup New Branch",
        update_branch: "Update Branch",
        delete_branch_confirm: "Are you sure you want to delete this branch? This might affect linked data like orders and inventory.",
        table_qr_setup: "Table QR Setup",
        manage_table_qr: "Generate and manage unique QR codes for each table",
        add_table: "Add Table",
        table_number_name: "Table Number / Name",
        generate_table_qr: "Generate Table QR",
        view_qr: "View QR",
        print_qr_tag: "Print QR Tag",
        copy_link: "Copy Link",
        open_menu: "Open Menu",
        qr_status: "QR Status",
        ready: "READY",
        missing: "MISSING",
        remove_table_confirm: "This will permanently delete this table's QR setup.",
        confirm_delete: "Confirm Deletion",
        success: "Success",
        failed: "Failed",
        invalid_image_format: "Only image files are allowed",
        image_size_too_large: "Image size must be less than 2MB",
        user_management: "User Management",
        staff_identity: "Staff Identity",
        business_role: "Business Role",
        contact_branch: "Contact / Branch",
        access_status: "Access Status",
        management: "Management",
        active_branches: "Active Branches",
        total_personnel: "Total Personnel",
        regular_team: "Regular Team",
        expires: "Expires",
        staff_nodes: "Staff Nodes",
        lookup_placeholder: "Lookup by name/id...",
        new_staff_member: "New Staff Member",
        update_staff: "Update Staff",
        purge: "Purge",
        view_only: "View Only",
        permitted: "Permitted",
        suspended: "Suspended",
        all_staff: "All Staff",
        executives: "Executives",
        admins: "Admins",
        staff_limit_reached: "Staff limit reached for your plan",
        required: "is required",
        password_not_match: "Passwords do not match",
        user_role: "User Role",
        owner: "Owner",
        executive: "Executive",
        security_permissions: "Security & Permissions",
        security_permissions_desc: "Control what each user role can access across branches",
        select_user_role: "Select User Role",
        user_role_desc: "Permissions will apply to all users assigned to this role.",
        pick_role_placeholder: "Pick a role to configure",
        multi_branch_access: "Multi-Branch Access",
        multi_branch_access_desc: "Permissions defined here are universal across all branches. Staff will only see data for their assigned branch.",
        module_permissions: "Module Permissions",
        select_all: "Select All",
        permission_name: "Permission Name",
        navigation_path: "Navigation Path",
        upload: "Upload",
        yes: "Yes",
        no: "No",
        branch_management_desc: "Global control center for multi-branch operations and executive oversight.",
        staff_management_desc: "Manage your business team, roles, and administrative access.",
        password: "Password",
        report: "Report",
        pending_table: "Pending Table",
        sound_on: "Sound On",
        sound_off: "Sound Off",
        need_restock: "Need to re-stock",
        purchase_receipt: "Purchase Receipt",
        dine_in: "Dine In",
        take_away: "Take Away",
        customer_name: "Customer Name",
        table_label: "Table",
        order_list: "Order List",
        cart_empty: "Cart is empty",
        add_from_menu: "Add items from the menu",
        payment_details: "Payment Details",
        total_savings: "Total Savings",
        tax_fees: "Tax & Fees",
        select_payment: "Select payment",
        place_order: "Place Order",
        customize_coffee: "Customize Your Coffee",
        mood: "Mood",
        size: "Size",
        sugar_level: "Sugar Level",
        order_completed: "Order completed!",
        order_placed: "Order placed successfully!",
        new_order_received: "New order received from table!",
        hot: "Hot",
        ice: "Ice",
        available: "Available",
        pending_orders: "Pending Table Orders",
        no_pending: "No pending table orders",
        walk_in: "Walk-in",
        guest: "Guest",
        refresh_list: "Refresh List",
        unknown: "Unknown",
        no_discount: "No Discount",
        update: "Update",
        order_failed: "Order failed!",
        fetch_branch_failed: "Failed to fetch branches",
        fetch_table_failed: "Failed to fetch tables",
        operation_failed: "Operation failed",
        scan_menu_order: "Scan to view Menu & Order",
        recipe: "Recipe",
        audit: "Audit",
        off: "Off",
        update_item: "Update Item",
        save_item: "Save Item",
        choose_size: "Choose Size",
        label_required: "Label required",
        price_required: "Price required",
        category_required: "Category required",
        enter_description: "Enter product description",
        view: "View",
        performance_trends: "Performance Trends",
        top_selling_products: "Top Selling Products",
        system_distribution: "System Distribution",
        total_revenue_growth: "Total Revenue Growth",
        customer_retention: "Customer Retention",
        not_specified: "Not Specified",
        no_phone: "No Phone",
        create_branch: "Create Branch",
        free_plan_limit: "Free Plan users are limited to 1 branch. Upgrade to Pro for multi-location support.",
        pro_plan_info: "You are on the Pro Plan. You can manage multiple branches seamlessly.",
        goods_received_success: "Goods received and stock updated!",
        create_purchase_failed: "Failed to create purchase",
        receive_goods_failed: "Failed to receive goods",
        something_went_wrong: "Something went wrong",
        confirm_remove_raw_material: "Are you sure you want to remove this raw material?",
        no_image: "No Img",
        khqr_setting: "KHQR Setting",
        upload_khqr: "Upload KHQR",
        khqr_image: "KHQR Image",
        daily_closing_title: "Daily Closing & Orders",
        daily_closing_desc: "Review daily sales and reconcile your accounts",
        total_orders_label: "Total Orders",
        dash_cash: "Cash",
        dash_aba: "ABA / QR",
        dash_wing: "Wing / Others",
        top_selling_label: "Top Selling",
        tab_today: "Today/Closing",
        tab_history: "Shift History",
        add_expense_btn: "Add Expense",
        save_print_report: "Save & Print Shift Report",
        open_shift_btn: "Open Shift",
        opening_cash_label: "Opening Cash",
        opening_cash_sub: "Initial Balance",
        actual_cash_label: "Actual Cash in Hand",
        cash_in_drawer: "Cash in Drawer",
        cash_sales_label: "Cash Sales",
        cash_expenses_label: "Cash Expenses",
        exchange_rate_label: "Exchange Rate",
        remark_placeholder: "Remark / Notes (e.g. customer owes, missing change...)",
        difference_label: "Difference",
        expected_label: "Expected",
        orders_this_shift: "Orders for this shift",
        refresh_btn: "Refresh",
        close_date: "Close Date",
        staff_role_label: "Staff / Role",
        actual_in_drawer: "Actual In Drawer",
        total_sales_all: "Total Sales (All)",
        order_detail_title: "Enhanced Order Detail",
        order_summary: "Order Summary",
        items_ordered: "Items Ordered",
        quick_expense_title: "Quick Expense",
        expense_amount: "Expense Amount",
        payment_type: "Payment Type",
        expense_cash_desc: "Cash / From Drawer",
        expense_bank_desc: "Bank / QR (Doesn't affect cash)",
        describe_expense: "Describe the expense (e.g. Bought ice)",
        open_new_shift: "Open New Shift",
        enter_opening_cash: "Enter your opening cash to start",
        authorized_by: "Authorized By",
        open_shift_now: "Open Shift Now",
        home_boutique: "Boutique",
        discover: "Discover",
        starred: "Starred",
        profile_atelier: "Atelier",
        selected_collections: "Selected collections",
        house_favorites: "House Favorites",
        pure_perfection: "Pure perfection in every cup",
        taste_luxury: "Taste the Luxury of",
        fine_beans: "Fine Beans",
        signature_limited: "Experience our signature limited edition brew, curated for premium members.",
        explore_now: "Explore Now",
        search_product: "Discover your coffee...",
        search_results: "Found for You",
        related_products: "You Might Also Like",
        established: "Established",
        basket_empty: "Basket is currently empty",
        your_basket: "Your Basket",
        place_order_now: "Place Order Now",
        subview_history: "Order History",
        subview_settings: "App Settings",
    },
    kh: {
        dashboard: "ផ្ទាំងគ្រប់គ្រង",
        subscription: "គម្រោងប្រើប្រាស់",
        inventory: "ស្តុកទំនិញ",
        purchases: "ទិញទំនិញចូល",
        suppliers: "អ្នកផ្គត់ផ្គង់",
        stock: "ស្តុក",
        stock_logs: "ប្រវត្តិកែសម្រួលស្តុក",
        pos: "ការលក់ (POS)",
        branches: "សាខានីមួយៗ",
        tables: "តុក និង កូដ QR",
        products: "មុខទំនិញ",
        categories: "ប្រភេទមុខទំនិញ",
        order_history: "ប្រវត្តិនៃការកុម្ម៉ង់",
        staff_roles: "បុគ្គលិក និងសិទ្ធិ",
        users: "បុគ្គលិក",
        roles: "មុខដំណែង",
        permissions: "សិទ្ធិប្រើប្រាស់",
        plans: "ជម្រើសគម្រោង",
        reports: "របាយការណ៍",
        sales_report: "របាយការណ៍លក់",
        expenses: "ការចំណាយ",
        best_sellers: "ទំនិញលក់ដាច់",
        settings: "ការកំណត់",
        business: "ប្រព័ន្ធអាជីវកម្ម",
        logout: "ចាកចេញ",
        profile: "ព័ត៌មានផ្ទាល់ខ្លួន",
        executive_dashboard: "ផ្ទាំងគ្រប់គ្រងព័ត៌មានសង្ខេប",
        real_time_metrics: "ទិន្នន័យលក់ និងដំណើរការអាជីវកម្មសរុប",
        apply_filters: "ប្រើប្រាស់ចម្រោះ",
        search: "ស្វែងរក",
        recent_activity: "សកម្មភាពថ្មីៗ",
        view_all_orders: "មើលការកុម្ម៉ង់ទាំងអស់",
        no_data: "មិនមានទិន្នន័យ",
        customer_overview: "ទិដ្ឋភាពអតិថិជន",
        financial_summary: "សង្ខេបហិរញ្ញវត្ថុ",
        sales_performance: "លទ្ធផលនៃការលក់",
        total: "សរុប",
        total_sales: "លក់សរុប",
        total_expenses: "ចំណាយសរុប",
        net_profit: "ចំណេញសុទ្ធ",
        order_count: "ចំនួនកុម្ម៉ង់",
        avg_transaction: "មធ្យមភាគលក់",
        profit_margin: "ភាគរយចំណេញ",
        performance_trends: "និន្នាការលទ្ធផល",
        revenue: "ចំណូល",
        growth: "កំណើន",
        distribution: "ការបែងចែក",
        live: "បច្ចុប្បន្ន",
        now: "អម្បាញ់មិញ",
        account_settings: "ការកំណត់គណនី",
        general_info: "ព័ត៌មានទូទៅ",
        full_name: "ឈ្មោះពេញ",
        email_address: "អុីមែល (Login ID)",
        security_settings: "ការកំណត់សុវត្ថិភាព",
        new_password: "លេខសម្ងាត់ថ្មី",
        confirm_password: "បញ្ជាក់លេខសម្ងាត់",
        leave_blank: "ទុកឱ្យនៅទទេប្រសិនបើមិនផ្លាស់ប្តូរ",
        save_changes: "រក្សាទុក",
        active_account: "គណនីសកម្ម",
        branch: "សាខា",
        business_label: "អាជីវកម្ម",
        order_no: "លេខកុម្ម៉ង់",
        date: "កាលបរិច្ឆេទ",
        status: "ស្ថានភាព",
        amount: "ចំនួនទឹកប្រាក់",
        payment_method: "ការទូទាត់",
        cashier: "អ្នកគិតលុយ",
        all: "ទាំងអស់",
        pending: "រង់ចាំ",
        paid: "បង់រួច",
        cancelled: "បោះបង់",
        view_details: "មើលលម្អិត",
        order_details: "លម្អិតការកុម្ម៉ង់",
        subtotal: "សរុបរង",
        tax: "ពន្ធ",
        discount: "បញ្ចុះតម្លៃ",
        print: "បោះពុម្ព",
        export: "ទាញយក",
        filter: "ចម្រោះ",
        items: "មុខ",
        no_orders: "រកមិនឃើញការកុម្ម៉ង់ទេ",
        order_management: "គ្រប់គ្រងការកុម្ម៉ង់",
        track_orders: "តាមដាន និងគ្រប់គ្រងការកុម្ម៉ង់របស់អ្នកឱ្យមានប្រសិទ្ធភាព",
        avg_order_value: "តម្លៃមធ្យមកុម្ម៉ង់",
        this_month: "ខែនេះ",
        total_revenue: "ចំណូលសរុប",
        subscription_limits: "ការជាវ និងដែនកំណត់របស់ខ្ញុំ",
        overview: "ទិដ្ឋភាពទូទៅ",
        billing_history: "ប្រវត្តិនៃការបង់ប្រាក់",
        current_trial: "ការសាកល្បងបច្ចុប្បន្ន",
        current_package: "កញ្ចប់បច្ចុប្បន្ន",
        package_30_day_trial: "សាកល្បងប្រើ ៣០ថ្ងៃ",
        started: "ចាប់ផ្តើមនៅ",
        expires_on: "ផុតកំណត់នៅ",
        no_expiry: "គ្មានថ្ងៃផុតកំណត់",
        days_remaining: "ថ្ងៃនៅសល់",
        days_ago: "ថ្ងៃមុន",
        expired_label: "ផុតកំណត់",
        upgrade_plan: "ដំឡើងគម្រោង",
        resource_utilization: "ការប្រើប្រាស់ធនធាន",
        staff_seats: "ចំនួនបុគ្គលិក",
        store_branches: "ចំនួនសាខា",
        sku_capacity: "ចំនួនមុខទំនិញ (Products)",
        unlimited: "មិនកំណត់",
        need_more_capacity: "ត្រូវការបន្ថែមមែនទេ? ការដំឡើងចំណាយពេលតិចជាង ១ នាទី។",
        compare_plans: "ប្រៀបធៀបគម្រោង",
        subscription_history: "ប្រវត្តិនៃការជាវ",
        history_desc: "រាល់រយៈពេលនៃការជាវកន្លងមក និងបច្ចុប្បន្នរបស់អ្នក។",
        refresh: "ផ្ទុកឡើងវិញ",
        price: "តម្លៃ",
        duration: "រយៈពេល",
        not_available: "មិនអាចប្រើបាន",
        current: "បច្ចុប្បន្ន",
        maybe_later: "ទុកពេលក្រោយ",
        next_confirm: "បន្ទាប់៖ បញ្ជាក់ការដំឡើង →",
        currently_active: "កំពុងប្រើប្រាស់",
        upgrade_picker_desc: "ជ្រើសរើសគម្រោងដែលសាកសមនឹងតម្រូវការអាជីវកម្មរបស់អ្នក។ សិទ្ធិ និងដែនកំណត់នឹងត្រូវបានធ្វើបច្ចុប្បន្នភាពភ្លាមៗ។",
        upgrading_to: "កំពុងដំឡើងទៅ",
        month: "ខែ",
        relogin_required: "តម្រូវឱ្យចូលគណនីម្តងទៀត",
        relogin_desc: "សូមចាកចេញ និងចូលគណនីម្តងទៀត ដើម្បីដំណើរការសិទ្ធិ និងមុខងារថ្មីៗរបស់អ្នក។",
        upgrade_success: "ការដំឡើងបានជោគជ័យ! 🎉",
        full_access_to: "ឥឡូវនេះអ្នកមានសិទ្ធិចូលប្រើពេញលេញទៅកាន់",
        active_until: "មានសុពលភាពរហូតដល់",
        got_it: "យល់ព្រម! 🚀",
        days: "ថ្ងៃ",
        one_time: "ការទិញផ្តាច់",
        lifetime: "ផ្តាច់",
        permanent_access: "ប្រើប្រាស់ជារៀងរហូត",
        product_list: "បញ្ជីមុខទំនិញ",
        add_new_product: "បន្ថែមមុខទំនិញថ្មី",
        edit_product: "កែសម្រួលមុខទំនិញ",
        search_product: "ស្វែងរកមុខទំនិញ...",
        product_name: "ឈ្មោះមុខទំនិញ",
        category_name: "ឈ្មោះប្រភេទ",
        quantity: "បរិមាណ",
        barcode: "បាកូដ",
        description: "ការពិពណ៌នា",
        image: "រូបភាព",
        action: "សកម្មភាព",
        confirm_delete_product: "តើអ្នកពិតជាចង់លុបមុខទំនិញនេះមែនទេ?",
        product_deleted: "បានលុបមុខទំនិញដោយជោគជ័យ",
        product_saved: "បានរក្សាទុកមុខទំនិញដោយជោគជ័យ",
        remove_data: "លុបទិន្នន័យ",
        confirm_remove_product: "តើអ្នកពិតជាចង់លុបមុខទំនិញនេះមែនទេ?",
        total_products: "មុខទំនិញសរុប",
        menu_inventory: "បញ្ជីមុខទំនិញលក់",
        add_new: "បន្ថែមថ្មី",
        brand: "ម៉ាក",
        edit_product_title: "☕ កែសម្រួលមុខទំនិញ",
        new_menu_item: "☕ បន្ថែមម្ហូប/ភេសជ្ជៈថ្មី",
        sizes: "ទំហំ",
        add_size: "បន្ថែមទំហំ",
        addons: "គ្រឿងបន្ថែម",
        add_addon: "បន្ថែមគ្រឿងបន្ថែម",
        customize_coffee: "ការកំណត់ជម្រើសបន្ថែម",
        mood: "ប្រភេទ / Mood",
        hot: "ក្តៅ",
        iced: "ត្រជាក់",
        frappe: "ក្រឡុក",
        sizes_override_msg: "* ប្រសិនបើមានកំណត់តម្លៃតាមទំហំខាងក្រោម វានឹងប្រើជំនួសតម្លៃគោលក្នុង POS (Sizes override Base Price).",
        base_price_label: "តម្លៃគោល",
        save_item: "រក្សាទុកទំនិញ",
        update_item: "កែសម្រួលទំនិញ",
        purchase: "ការទិញ",
        supplier: "អ្នកផ្គត់ផ្គង់",
        raw_material: "វត្ថុធាតុដើម",
        invoices: "វិក្កយបត្រ",
        shop_managment: "ការគ្រប់គ្រងហាង",
        table: "តុ",
        product: "ផលិតផល",
        category: "ប្រភេទ",
        sale: "លក់",
        order: "ការកុម្ម៉ង់",
        user: "អ្នកប្រើប្រាស់",
        permission: "សិទ្ធិ",
        total_purchase: "ការទិញសរុប",
        total_paid: "ការបង់សរុប",
        outstanding_balance: "សមតុល្យនៅសល់",
        total_orders: "ការកុម្ម៉ង់សរុប",
        purchase_history: "ប្រវត្តិនៃការទិញ",
        new_purchase: "ការទិញថ្មី",
        ref_no: "លេខយោង",
        paid_amount: "ចំនួនបានបង់",
        balance: "សមតុល្យ",
        save: "រក្សាទុក",
        cancel: "បោះបង់",
        receive_date: "ថ្ងៃទទួល",
        note: "ចំណាំ",
        total_amount: "សរុបទឹកប្រាក់",
        receiving_now: "កំពុងទទួល",
        supplier_list: "បញ្ជីអ្នកផ្គត់ផ្គង់",
        name: "ឈ្មោះ",
        code: "កូដ",
        tel: "ទូរស័ព្ទ",
        email: "អ៊ីមែល",
        address: "អាសយដ្ឋាន",
        website: "គេហទំព័រ",
        created_at: "កាលបរិច្ឆេទបង្កើត",
        edit: "កែសម្រួល",
        delete: "លុប",
        add_new_supplier: "អ្នកផ្គត់ផ្គង់ថ្មី",
        edit_supplier: "កែសម្រួលអ្នកផ្គត់ផ្គង់",
        confirm_delete_supplier: "តើអ្នកប្រាកដថាចង់លុបទិន្នន័យនេះឬ?",
        supplier_deleted: "លុបទិន្នន័យដោយជោគជ័យ!",
        raw_material_list: "បញ្ជីគ្រឿងផ្សំ",
        material_name: "ឈ្មោះគ្រឿងផ្សំ",
        stock_status: "ស្ថានភាពស្តុក",
        last_cost: "ថ្លៃដើមចុងក្រោយ",
        active: "ដំណើរការ",
        inactive: "មិនដំណើរការ",
        add_new_material: "បន្ថែមគ្រឿងផ្សំថ្មី",
        edit_material: "កែសម្រួលគ្រឿងផ្សំ",
        initial_stock: "ស្តុកដំបូង",
        min_stock_alert: "ការជូនដំណឹងស្តុកទាប",
        in_stock: "មានក្នុងស្តុក",
        low_stock: "ស្តុកទាប",
        out_of_stock: "អស់ពីស្តុក",
        total_products_menu: "មុខម្ហូបទាំងអស់",
        low_stock_products: "មុខម្ហូបស្តុកទាប",
        low_stock_materials: "គ្រឿងផ្សំស្តុកទាប",
        stock_logs_adjustments: "កំណត់ត្រាស្តុក និងការកែម្រួល",
        manual_adjustment: "ការកែម្រួលដោយដៃ",
        filter_by_item_type: "ចម្រោះតាមប្រភេទ",
        filter_by_type: "ចម្រោះតាមប្រតិបត្តិការ",
        date_time: "ថ្ងៃ និងម៉ោង",
        category: "ប្រភេទផលិតផល",
        transaction: "ប្រតិបត្តិការ",
        change: "ការផ្លាស់ប្តូរ",
        staff: "បុគ្គលិក",
        reason: "មូលហេតុ",
        stock_correction: "ការកែម្រួលស្តុក",
        inventory_item_type: "ប្រភេទរបស់របរ",
        select_item: "ជ្រើសរើសរបស់របរ",
        action_type: "ប្រភេទសកម្មភាព",
        qty_change: "ចំនួនផ្លាស់ប្តូរ",
        remark_reason: "សម្គាល់ / មូលហេតុ",
        adjustment: "ការកែម្រួល",
        waste: "ការបាត់បង់/ខូច",
        receive: "ការទទួល",
        branch_management: "ការគ្រប់គ្រងសាខា",
        manage_locations: "គ្រប់គ្រងទីតាំងអាជីវកម្ម និងទីស្នាក់ការរបស់អ្នក",
        add_new_branch: "បន្ថែមសាខាថ្មី",
        branch_name: "ឈ្មោះសាខា",
        location_address: "ទីតាំង / អាសយដ្ឋាន",
        contact_phone: "លេខទូរស័ព្ទទំនាក់ទំនង",
        set_as_main_hq: "កំណត់ជាទីស្នាក់ការកណ្តាល?",
        main_headquarter: "ទីស្នាក់ការកណ្តាល",
        setup_new_branch: "រៀបចំសាខាថ្មី",
        update_branch: "កែសម្រួលសាខា",
        delete_branch_confirm: "តើអ្នកប្រាកដថាចង់លុបសាខានេះមែនទេ? វានឹងអាចប៉ះពាល់ដល់ទិន្នន័យពាក់ព័ន្ធដូចជាការបញ្ជាទិញ និងស្តុក។",
        table_qr_setup: "ការរៀបចំ QR តុ",
        manage_table_qr: "បង្កើត និងគ្រប់គ្រងកូដ QR សម្រាប់តុនីមួយៗ",
        add_table: "បន្ថែមតុ",
        table_number_name: "លេខតុ / ឈ្មោះតុ",
        generate_table_qr: "បង្កើត QR តុ",
        order_detail: "លម្អិតការបញ្ជាទិញ",
        view_qr: "មើល QR",
        print_qr_tag: "បោះពុម្ព QR តុ",
        copy_link: "ចម្លងតំណភ្ជាប់",
        open_menu: "បើកមុខម្ហូប",
        qr_status: "ស្ថានភាព QR",
        ready: "រួចរាល់",
        missing: "បាត់",
        remove_table_confirm: "វានឹងលុបការរៀបចំ QR របស់តុនេះជាអចិន្ត្រៃយ៍។",
        confirm_delete: "បញ្ជាក់ការលុប",
        success: "ជោគជ័យ",
        failed: "បរាជ័យ",
        invalid_image_format: "អនុញ្ញាតតែឯកសាររូបភាពប៉ុណ្ណោះ",
        image_size_too_large: "ទំហំរូបភាពត្រូវតែតូចជាង ២មេកាបៃ",
        user_management: "ការគ្រប់គ្រងអ្នកប្រើប្រាស់",
        staff_identity: "អត្តសញ្ញាណបុគ្គលិក",
        business_role: "តួនាទីអាជីវកម្ម",
        contact_branch: "ទំនាក់ទំនង / សាខា",
        access_status: "ស្ថានភាពចូលប្រើ",
        management: "ការគ្រប់គ្រង",
        active_branches: "សាខាសកម្ម",
        total_personnel: "បុគ្គលិកសរុប",
        regular_team: "ក្រុមធម្មតា",
        expires: "ផុតកំណត់",
        staff_nodes: "ចំនួនបុគ្គលិក",
        lookup_placeholder: "ស្វែងរកតាមឈ្មោះ/លេខសម្គាល់...",
        new_staff_member: "សមាជិកបុគ្គលិកថ្មី",
        update_staff: "កែសម្រួលបុគ្គលិក",
        purge: "លុបចោល",
        view_only: "មើលតែប៉ុណ្ណោះ",
        permitted: "អនុញ្ញាត",
        suspended: "ផ្អាក",
        all_staff: "បុគ្គលិកទាំងអស់",
        executives: "នាយកប្រតិបត្តិ",
        admins: "អ្នកគ្រប់គ្រង",
        staff_limit_reached: "ចំនួនបុគ្គលិកដល់ដែនកំណត់សម្រាប់គម្រោងរបស់អ្នក",
        required: "តម្រូវឱ្យមាន",
        password_not_match: "លេខសម្ងាត់មិនត្រូវគ្នា",
        user_role: "តួនាទី",
        owner: "ម្ចាស់ហាង",
        executive: "នាយកប្រតិបត្តិ",
        security_permissions: "សុវត្ថិភាព និងសិទ្ធិអនុញ្ញាត",
        security_permissions_desc: "គ្រប់គ្រងអ្វីដែលតួនាទីអ្នកប្រើប្រាស់នីមួយៗអាចចូលប្រើប្រាស់បាននៅគ្រប់សាខា",
        select_user_role: "ជ្រើសរើសតួនាទីអ្នកប្រើប្រាស់",
        user_role_desc: "សិទ្ធិអនុញ្ញាតនឹងត្រូវបានអនុវត្តចំពោះអ្នកប្រើប្រាស់ទាំងអស់ដែលបានចាត់តាំងឱ្យតួនាទីនេះ។",
        pick_role_placeholder: "ជ្រើសរើសតួនាទីដើម្បីកំណត់រចនាសម្ព័ន្ធ",
        multi_branch_access: "ការចូលប្រើប្រាស់ច្រើនសាខា",
        multi_branch_access_desc: "សិទ្ធិអនុញ្ញាតដែលបានកំណត់នៅទីនេះគឺមានលក្ខណៈជាសកលនៅគ្រប់សាខាទាំងអស់។ បុគ្គលិកនឹងឃើញតែទិន្នន័យសម្រាប់សាខាដែលបានចាត់តាំងរបស់ពួកគេប៉ុណ្ណោះ។",
        module_permissions: "សិទ្ធិអនុញ្ញាតម៉ូឌុល",
        select_all: "ជ្រើសរើសទាំងអស់",
        permission_name: "ឈ្មោះសិទ្ធិ",
        navigation_path: "ផ្លូវរុករក",
        upload: "បង្ហោះ",
        yes: "បាទ/ចាស់",
        no: "ទេ",
        branch_management_desc: "មជ្ឈមណ្ឌលគ្រប់គ្រងសកលសម្រាប់ប្រតិបត្តិការច្រើនសាខា និងការត្រួតពិនិត្យប្រតិបត្តិ។",
        staff_management_desc: "គ្រប់គ្រងក្រុមអាជីវកម្ម តួនាទី និងការចូលប្រើប្រាស់រដ្ឋបាលរបស់អ្នក។",
        password: "លេខសម្ងាត់",
        report: "របាយការណ៍",
        pending_table: "តុរង់ចាំ",
        sound_on: "សំឡេងបើក",
        sound_off: "សំឡេងបិទ",
        need_restock: "ត្រូវការបំពេញស្តុក",
        purchase_receipt: "វិក្កយបត្រទិញ",
        dine_in: "ញ៉ាំក្នុងហាង",
        take_away: "ខ្ចប់ទៅផ្ទះ",
        customer_name: "ឈ្មោះអតិថិជន",
        table_label: "តុ",
        order_list: "បញ្ជីកុម្ម៉ង់",
        cart_empty: "កន្ត្រកទំនេរ",
        add_from_menu: "បន្ថែមមុខម្ហូបពីបញ្ជី",
        payment_details: "ព័ត៌មានទូទាត់",
        total_savings: "ការសន្សំសរុប",
        tax_fees: "ពន្ធ និងសេវាកម្ម",
        select_payment: "ជ្រើសរើសការទូទាត់",
        place_order: "បញ្ជាទិញ",
        customize_coffee: "កំណត់កាហ្វេរបស់អ្នក",
        mood: "ប្រភេទ",
        size: "ទំហំ",
        sugar_level: "កម្រិតស្ករ",
        order_completed: "ការកុម្ម៉ង់បានបញ្ចប់!",
        order_placed: "ការកុម្ម៉ង់បានជោគជ័យ!",
        new_order_received: "មានការកុម្ម៉ង់ថ្មីពីតុ!",
        hot: "ក្តៅ",
        ice: "ត្រជាក់",
        available: "អាចប្រើបាន",
        pending_orders: "រង់ចាំបញ្ជាទិញពីតុ",
        no_pending: "មិនមានការបញ្ជាទិញទេ",
        walk_in: "ចូលទិញផ្ទាល់",
        guest: "ភ្ញៀវ",
        refresh_list: "ទាញយកឡើងវិញ",
        unknown: "មិនស្គាល់",
        no_discount: "គ្មានការបញ្ចុះតម្លៃ",
        update: "កែសម្រួល",
        order_failed: "ការកុម្ម៉ង់បរាជ័យ!",
        fetch_branch_failed: "បរាជ័យក្នុងការទាញយកសាខា",
        fetch_table_failed: "បរាជ័យក្នុងការទាញយកតុ",
        operation_failed: "ប្រតិបត្តិការបរាជ័យ",
        scan_menu_order: "ស្កែនដើម្បីមើលបញ្ជីម្ហូប និងកុម្ម៉ង់",
        recipe: "រូបមន្ត",
        audit: "សវនកម្ម",
        off: "បិទ",
        update_item: "កែសម្រួលទំនិញ",
        save_item: "រក្សាទុកទំនិញ",
        choose_size: "ជ្រើសរើសទំហំ",
        label_required: "តម្រូវឱ្យមានស្លាក",
        price_required: "តម្រូវឱ្យមានតម្លៃ",
        category_required: "តម្រូវឱ្យមានប្រភេទ",
        enter_description: "បញ្ជាក់ការពិពណ៌នា",
        view: "មើល",
        performance_trends: "និន្នាការលទ្ធផល",
        top_selling_products: "ផលិតផលលក់ដាច់បំផុត",
        system_distribution: "ការបែងចែកប្រព័ន្ធ",
        total_revenue_growth: "កំណើនចំណូលសរុប",
        customer_retention: "ការរក្សាអតិថិជន",
        not_specified: "មិនបានបញ្ជាក់",
        no_phone: "គ្មានលេខទូរស័ព្ទ",
        create_branch: "បង្កើតសាខា",
        free_plan_limit: "អ្នកប្រើប្រាស់គម្រោងឥតគិតថ្លៃត្រូវបានកំណត់ត្រឹម ១ សាខាប៉ុណ្ណោះ។ សូមដំឡើងទៅ Pro សម្រាប់ការគាំទ្រច្រើនទីតាំង។",
        pro_plan_info: "អ្នកកំពុងប្រើប្រាស់គម្រោង Pro។ អ្នកអាចគ្រប់គ្រងសាខាច្រើនបានយ៉ាងរលូន។",
        goods_received_success: "ទំនិញត្រូវបានទទួល និងធ្វើបច្ចុប្បន្នភាពស្តុក!",
        create_purchase_failed: "បរាជ័យក្នុងការបង្កើតការទិញ",
        receive_goods_failed: "បរាជ័យក្នុងការទទួលទំនិញ",
        something_went_wrong: "មានបញ្ហាអ្វីមួយបានកើតឡើង",
        confirm_remove_raw_material: "តើអ្នកប្រាកដថាចង់លុបគ្រឿងផ្សំនេះមែនទេ?",
        no_image: "គ្មានរូបភាព",
        khqr_setting: "កំណត់កូដ QR ទូទាត់",
        upload_khqr: "បង្ហោះកូដ QR (KHQR)",
        khqr_image: "រូបភាពកូដ QR",
        daily_closing_title: "ការបិទបញ្ជីប្រចាំថ្ងៃ និងការបញ្ជាទិញ",
        daily_closing_desc: "ពិនិត្យមើលការលក់ប្រចាំថ្ងៃ និងផ្ទៀងផ្ទាត់បញ្ជី",
        total_orders_label: "សរុបបុង",
        dash_cash: "សាច់ប្រាក់",
        dash_aba: "ABA / QR",
        dash_wing: "Wing / ផ្សេងៗ",
        top_selling_label: "លក់ដាច់បំផុត",
        tab_today: "បិទបញ្ជីថ្ងៃនេះ",
        tab_history: "ប្រវត្តិនៃការបិទបញ្ជី",
        add_expense_btn: "បន្ថែមការចំណាយ",
        save_print_report: "រក្សាទុក និងបោះពុម្ព",
        open_shift_btn: "បើកថ្ងៃ",
        opening_cash_label: "លុយដើមគ្រា",
        opening_cash_sub: "សមតុល្យដើម",
        actual_cash_label: "លុយក្នុងថត",
        cash_in_drawer: "លុយក្នុងដៃជាក់ស្តែង",
        cash_sales_label: "លក់ជាសាច់ប្រាក់",
        cash_expenses_label: "ការចំណាយជាសាច់ប្រាក់",
        exchange_rate_label: "អត្រាប្តូរប្រាក់",
        remark_placeholder: "សម្គាល់ / 备注 (ឧទាហរណ៍៖ អតិថិជនជំពាក់ ឬបាត់លុយអាប់...)",
        difference_label: "ភាពខុសគ្នា",
        expected_label: "តុល្យភាពរំពឹងទុក",
        orders_this_shift: "ការបញ្ជាទិញក្នុងវេននេះ",
        refresh_btn: "ផ្ទុកឡើងវិញ",
        close_date: "ថ្ងៃបិទបញ្ជី",
        staff_role_label: "បុគ្គលិក / តួនាទី",
        actual_in_drawer: "លុយជាក់ស្តែង",
        total_sales_all: "លក់សរុបទាំងអស់",
        order_detail_title: "ព័ត៌មានលម្អិតបុង",
        order_summary: "សង្ខេបការបញ្ជាទិញ",
        items_ordered: "មុខទំនិញដែលបានកុម្ម៉ង់",
        quick_expense_title: "ចំណាយរហ័ស",
        expense_amount: "ចំនួនទឹកប្រាក់ចំណាយ",
        payment_type: "ប្រភេទនៃការទូទាត់",
        expense_cash_desc: "សាច់ប្រាក់ (ដកពីថត)",
        expense_bank_desc: "ធនាគារ / QR (មិនប៉ះសាច់ប្រាក់)",
        describe_expense: "ការពិពណ៌នាពីការចំណាយ (ឧទាហរណ៍៖ ទិញទឹកកក)",
        open_new_shift: "ការបើកវេនថ្មី",
        enter_opening_cash: "បញ្ចូលទឹកប្រាក់ដើមគ្រារបស់អ្នកដើម្បីចាប់ផ្តើម",
        authorized_by: "អនុញ្ញាតដោយ",
        open_shift_now: "បើកបញ្ជីឥឡូវនេះ",
        home_boutique: "ការបញ្ជាទិញ",
        discover: "ស្វែងរក",
        starred: "ចំណូលចិត្ត",
        profile_atelier: "គណនី",
        selected_collections: "បណ្តុំដែលបានជ្រើសរើស",
        house_favorites: "ភេសជ្ជៈពិសេសប្រចាំហាង",
        pure_perfection: "រសជាតិដ៏ល្អឥតខ្ចោះគ្រប់ពែង",
        taste_luxury: "រសជាតិដ៏ប្រណិតនៃ",
        fine_beans: "គ្រាប់កាហ្វេគុណភាព",
        signature_limited: "សាកល្បងរសជាតិអាថ៌កំបាំងដែលផលិតយ៉ាងសម្រិតសម្រាំងបំផុតសម្រាប់លោកអ្នក។",
        explore_now: "ស្វែងរកឥឡូវនេះ",
        search_product: "ស្វែងរកភេសជ្ជៈដែលអ្នកចូលចិត្ត...",
        search_results: "លទ្ធផលដែលរកឃើញ",
        related_products: "អ្នកប្រហែលជាចូលចិត្ត",
        established: "បង្កើតឡើងនៅឆ្នាំ",
        basket_empty: "មិនទាន់មានទំនិញក្នុងកន្ត្រកទេ",
        your_basket: "កន្ត្រករបស់អ្នក",
        place_order_now: "បញ្ជាទិញឥឡូវនេះ",
        subview_history: "ប្រវត្តិកុម្ម៉ង់",
        subview_settings: "ការកំណត់កម្មវិធី",
    },
};
